## Build the survey PDF.  Requires a TeX distribution (TeX Live / MiKTeX) with pdflatex + bibtex.
## The .tex is auto-assembled from draft/*.md by scripts/build_paper.py — edit the .md files,
## not 1bit-llm-survey.tex directly (it is regenerated).

MAIN = 1bit-llm-survey

## Pre-rendered standalone TikZ/pgfplots figures (figures/README.md): regenerated by
## `regen`, but must be compiled to PDF separately since each needs its own pdflatex
## process. Keeping this list in the Makefile, not just discovering figures/fig-*.tex
## with a glob, avoids silently picking up a stray/half-written file.
FIGS = fig-ste fig-growth fig-heatmap fig-weightyear fig-systemsvenn \
       fig-effbits fig-controlledpairs fig-efficiency-bars fig-efficiency-scatter

pdf: $(MAIN).pdf

$(MAIN).pdf: $(MAIN).tex references.bib
	pdflatex -interaction=nonstopmode $(MAIN).tex
	bibtex $(MAIN)
	pdflatex -interaction=nonstopmode $(MAIN).tex
	pdflatex -interaction=nonstopmode $(MAIN).tex

## Regenerate 1bit-llm-survey.tex + references.bib + tables/ + figures/fig-*.tex from
## the markdown drafts + CSVs. Run `figures` afterwards if any figure body changed.
regen:
	python scripts/build_paper.py

## Compile every pre-rendered figure's standalone .tex to PDF. Run after `regen` if the
## underlying data changed; commit the resulting figures/*.pdf alongside the .tex
## sources (Overleaf needs them as static assets, see figures/README.md).
figures:
	cd figures && for f in $(FIGS); do pdflatex -interaction=nonstopmode "$$f.tex"; done

clean:
	rm -f $(MAIN).aux $(MAIN).bbl $(MAIN).blg $(MAIN).log $(MAIN).out $(MAIN).toc
	cd figures && rm -f $(foreach f,$(FIGS),$(f).aux $(f).log)

.PHONY: pdf regen figures clean
